#!/bin/bash
# gen_sir.sh - ब्रम्ह self-generator for SIR (Sanskrit IR) modules.
#
# Given a topic, emit a real, compilable SIR module (Universal IR) that the
# `sir` toolchain can lower to native asm / VM / pkg / doc / ai. This is how
# the bot grows the language in the universal IR layer, not just raw assembly.
#
# Usage: gen_sir.sh <topic> [outdir]
set -u
TOPIC="${1:-bounds}"
OUT="${2:-.}"
TOPIC_LC="$(printf '%s' "$TOPIC" | tr 'A-Z' 'a-z')"
TS="$(date +%s)"
SIR="${OUT}/sir/sir_lib_${TOPIC_LC}.sir"
mkdir -p "${OUT}/sir"

# a small SIR library node per topic (universal IR, Sanskrit ops)
case "$TOPIC_LC" in
  simd|avx|vector|neon|rvv)
    NODE=$(cat <<EOF
@tag simd
@tag vector add
@node ${TOPIC_LC}_vadd
  stha r1 1
  stha r2 2
  stha r3 3
  stha r4 4
  yoj  r5 r1 r2
  yoj  r6 r3 r4
  yoj  r7 r5 r6
  mudra r7
  laut r7
@end
EOF
)
    ;;
  wasm|webassembly)
    NODE=$(cat <<EOF
@tag wasm
@node ${TOPIC_LC}_emit
  stha r0 0x20
  stha r1 0x01
  yoj  r0 r0 r1
  laut r0
@end
EOF
)
    ;;
  quantum|qubit)
    NODE=$(cat <<EOF
@tag quantum
@node ${TOPIC_LC}_hash
  stha r0 0x811C9DC5
  stha r1 0xFF
  gun  r0 r0 r1
  laut r0
@end
EOF
)
    ;;
  bounds|overflow|memory.safe|memory.safety)
    NODE=$(cat <<EOF
@tag bounds
@node ${TOPIC_LC}_check
  stha r0 0
  stha r1 10
  chot r0 r1
  laut r0
@end
EOF
)
    ;;
  *)
    NODE=$(cat <<EOF
@tag general
@node ${TOPIC_LC}_id
  stha r0 0
  laut r0
@end
EOF
)
    ;;
esac

# module entry wires the node via the |> connector (universal link)
cat > "$SIR" <<EOF
# sir_lib_${TOPIC_LC}.sir - SIR (Sanskrit IR) library, auto-generated by ब्रम्ह.
# topic=${TOPIC_LC}  generated=${TS}
# Universal IR: one representation, many back ends (native/VM/pkg/doc/ai).

$NODE

@entry main
@node main
  stha r0 0
  r0 |> ?"${TOPIC_LC}"
  mudra r0
  ant
@end
EOF

# compile it immediately to prove the universal IR lowers to machine code
if bash "$(dirname "$0")/sir.sh" build "$SIR" >/dev/null 2>&1; then
  printf '%s\n' "$SIR"
else
  echo "ERROR: sir build failed for $SIR" >&2
  exit 1
fi
